services:

  db:
    image: postgres:17.0-alpine3.20
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - app-network

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "alembic upgrade head && uvicorn app.web.app:create_app --host 0.0.0.0 --factory"


  test_db:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_DB: test_library_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"



networks:
  app-network:
