services:

  db:
    image: postgres:17.0-alpine3.20
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - app-network


  test_db:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_DB: test_library_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"



networks:
  app-network:
