"""renaming a column in a table LibraryCardModel

Revision ID: 269a4ba42d36
Revises: 42e6cea44a80
Create Date: 2025-06-11 09:49:21.057457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '269a4ba42d36'
down_revision: Union[str, None] = '42e6cea44a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('library_cards', 'return_data', new_column_name='return_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('library_cards', 'return_date', new_column_name='return_data')
    # ### end Alembic commands ###
