"""Added field desctiption to a books table

Revision ID: 42e6cea44a80
Revises: f748d3e155b2
Create Date: 2025-06-09 18:47:23.781447

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42e6cea44a80'
down_revision: Union[str, None] = 'f748d3e155b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['name'])
    op.add_column('books', sa.Column('description', sa.String(), server_default='No description', nullable=True))
    op.create_unique_constraint(None, 'books', ['isbn'])
    op.create_unique_constraint(None, 'readers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'readers', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'description')
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
